# Generated by Django 6.0.3 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscription_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='game_state',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Persistent frontend state (solved gates/challenges, shrine completions, boss flags).',
            ),
        ),
    ]
