# Generated by Django 6.0.3 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_playerprofile_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='game_state_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
