# Generated by Django 6.0.3 on 2026-05-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('concept', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('aria_tagline', models.CharField(blank=True, help_text="ARIA's first line about this region. Shown on the map.", max_length=300)),
                ('visual_theme', models.CharField(blank=True, help_text="CSS theme identifier applied to this region's tiles/palette.", max_length=50)),
                ('unlocked_by_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MemoryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('aria_memory_text', models.TextField(help_text="A piece of ARIA's backstory revealed when this fragment is collected.")),
                ('reward_description', models.CharField(blank=True, help_text='Describe any Tool or bonus unlocked by collecting this fragment.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_fragments', to='game.region')),
            ],
            options={
                'verbose_name': 'Memory Fragment',
                'verbose_name_plural': 'Memory Fragments',
                'ordering': ['region__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningShrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrines', to='game.region')),
            ],
            options={
                'verbose_name': 'Learning Shrine',
                'verbose_name_plural': 'Learning Shrines',
                'ordering': ['region__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('challenge_type', models.CharField(choices=[('fill_blank', 'Fill in the Blank'), ('bug_fix', 'Bug Fix'), ('open_code', 'Open Code'), ('boss', 'Boss Challenge')], max_length=20)),
                ('category', models.CharField(choices=[('gate', 'Challenge Gate'), ('boss_chamber', 'Boss Chamber'), ('roaming_bug', 'Roaming Bug Battle'), ('boss_bug', 'Boss Bug')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Display/encounter order within the region.')),
                ('prompt_code', models.TextField(help_text='The code template shown to the player. Use ___ for fill-in-the-blank gaps.')),
                ('solution_code', models.TextField(help_text='The complete correct solution. Shown only after two failed attempts.')),
                ('expected_output', models.TextField(help_text="The exact stdout produced when solution_code runs correctly. Pyodide compares the player's output to this string.")),
                ('hint_text', models.TextField(help_text='Text hint shown after the first wrong answer.')),
                ('lesson_reference', models.CharField(blank=True, help_text='e.g. "Code Library: Strings and Variable Assignment"', max_length=200)),
                ('aria_intro', models.TextField(help_text='What ARIA says when the player approaches this challenge.')),
                ('aria_hint', models.TextField(help_text='What ARIA says as a hint after the first wrong answer.')),
                ('aria_success', models.TextField(help_text='What ARIA says when the player submits a correct solution.')),
                ('aria_fail', models.TextField(help_text='What ARIA says when the player submits a wrong answer (second+ attempt).')),
                ('is_active', models.BooleanField(default=True)),
                ('available_in_practice', models.BooleanField(default=True, help_text='If True, this challenge appears in the standalone Practice Area.')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='game.region')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['region__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ShrineTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Lesson content in Markdown.')),
                ('code_example', models.TextField(blank=True, help_text='A runnable code example shown alongside the lesson.')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='game.learningshrine')),
            ],
            options={
                'verbose_name': 'Shrine Topic',
                'verbose_name_plural': 'Shrine Topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlayerChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='game.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to='accounts.playerprofile')),
            ],
            options={
                'verbose_name': 'Player Challenge Progress',
                'verbose_name_plural': 'Player Challenge Progress',
                'unique_together': {('player', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMemoryFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='game.memoryfragment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_fragments', to='accounts.playerprofile')),
            ],
            options={
                'verbose_name': 'Player Memory Fragment',
                'verbose_name_plural': 'Player Memory Fragments',
                'unique_together': {('player', 'fragment')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('line_reveal', 'Line Reveal'), ('syntax_check', 'Syntax Check'), ('aria_hint', 'ARIA Hint'), ('region_review', 'Region Review')], max_length=20)),
                ('uses_remaining', models.PositiveSmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='accounts.playerprofile')),
            ],
            options={
                'verbose_name': 'Player Tool',
                'verbose_name_plural': 'Player Tools',
                'unique_together': {('player', 'tool_type')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRegionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_progress', to='accounts.playerprofile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='game.region')),
            ],
            options={
                'verbose_name': 'Player Region Progress',
                'verbose_name_plural': 'Player Region Progress',
                'unique_together': {('player', 'region')},
            },
        ),
    ]
